language: elixir
elixir:
  - 1.4.5
otp_release:
  - 20.0
addons:
  - postgresql: '9.4'
env:
  - MIX_ENV=test
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
before_script:
  - mix ecto.setup
script:
  - mix test
